---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    app: jenkins-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: '8080'
      port: 8080
      targetPort: 8080
      nodePort: 30001